apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |-
      global
        chroot /var/lib/haproxy
        pidfile /var/run/haproxy.pid
        daemon
        maxconn 4096
        stats socket /run/haproxy/admin.sock mode 660 level admin

      defaults
        mode http
        balance leastconn
        retries 3
        option httpchk GET /health HTTP/1.0\r\nHost:\ app.example.com
        option http-server-close
        option dontlognull
        timeout connect    30ms
        timeout check    1000ms
        timeout client  30000ms
        timeout server  30000ms

      frontend stats
        bind *:26999
        mode http
        stats enable
        stats uri /

      frontend app.example.com-http
        bind *:8000
        log /dev/log local2 info
        option httplog

        # Only allow HTTPS unless internal
        acl HOST_internal hdr_reg(host) -i ^HAProxy
        redirect scheme https code 301 if !HOST_internal

        default_backend BACKEND_app

      frontend app.example.com-https
        bind *:9000 accept-proxy
        log /dev/log local2 info
        option httplog

        # HSTS
        http-request set-header X-Forwarded-For %[src]
        http-request set-header X-Forwarded-Proto https

        # Redirect to somewhere else if the domain is different
        acl HOST_app  hdr(host) -i app.example.com
        redirect location https://www.example.com/ code 301 if !HOST_app

        default_backend BACKEND_app

      backend BACKEND_app
        server app app:9000
